spring:
  application:
    name: example
  profiles:
    active: dev
#    active: prod
  jackson:
    time-zone: GMT+8

server:
  port: 8081
  servlet:
    context-path: /example
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain

